### 2. Python program to display IMDB’s Top rated 100 movies

In [2]:
from bs4 import BeautifulSoup
import requests

In [39]:
url = 'https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc'
url2 = 'https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc&start=51&ref_=adv_nxt'
page = requests.get(url)
page2 = requests.get(url2)
print(page)
print(page2)

<Response [200]>
<Response [200]>

In [40]:
soup = BeautifulSoup(page.content)
soup2 = BeautifulSoup(page2.content)
Name = []
Rating = []
#Year = []

for i in soup.find_all('div',class_='lister-item-content'):
    Name.append(i.find('a').text)
for i in soup2.find_all('div',class_='lister-item-content'):
    Name.append(i.find('a').text)

Name

['The Shawshank Redemption',
 'The Godfather',
 'Spider-Man: No Way Home',
 'The Dark Knight',
 'The Godfather: Part II',
 '12 Angry Men',
 'The Lord of the Rings: The Return of the King',
 'Pulp Fiction',
 "Schindler's List",
 'Inception',
 'Fight Club',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Forrest Gump',
 'Il buono, il brutto, il cattivo',
 'The Lord of the Rings: The Two Towers',
 'The Matrix',
 'Goodfellas',
 'Star Wars: Episode V - The Empire Strikes Back',
 "One Flew Over the Cuckoo's Nest",
 'Gisaengchung',
 'Interstellar',
 'Cidade de Deus',
 'Sen to Chihiro no kamikakushi',
 'Saving Private Ryan',
 'The Green Mile',
 'La vita è bella',
 'Se7en',
 'The Silence of the Lambs',
 'Star Wars',
 'Seppuku',
 'Shichinin no samurai',
 "It's a Wonderful Life",
 'Whiplash',
 'The Intouchables',
 'The Prestige',
 'The Departed',
 'The Pianist',
 'Gladiator',
 'American History X',
 'The Usual Suspects',
 'Léon',
 'The Lion King',
 'Terminator 2: Judgment Day',
 'Nuovo Cinema Paradiso',
 'Hotaru no haka',
 'Back to the Future',
 'Once Upon a Time in the West',
 'Psycho',
 'Rear Window',
 'Casablanca',
 'Modern Times',
 'City Lights',
 'Hamilton',
 'Capharnaüm',
 'Joker',
 'Kimi no na wa.',
 'Spider-Man: Into the Spider-Verse',
 'Avengers: Endgame',
 'Avengers: Infinity War',
 'Coco',
 'Django Unchained',
 'The Dark Knight Rises',
 '3 Idiots',
 'Taare Zameen Par',
 'WALL·E',
 'The Lives of Others',
 'Oldeuboi',
 'Memento',
 'Mononoke-hime',
 'Raiders of the Lost Ark',
 'The Shining',
 'Apocalypse Now',
 'Alien',
 'Tengoku to jigoku',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Witness for the Prosecution',
 'Paths of Glory',
 'Sunset Blvd.',
 'The Great Dictator',
 'Jagten',
 'Inglourious Basterds',
 'Eternal Sunshine of the Spotless Mind',
 'Requiem for a Dream',
 'American Beauty',
 'Good Will Hunting',
 'Toy Story',
 'Braveheart',
 'Reservoir Dogs',
 'Idi i smotri',
 'Aliens',
 'Once Upon a Time in America',
 'Amadeus',
 'Star Wars: Episode VI - Return of the Jedi',
 'Das Boot',
 '2001: A Space Odyssey',
 'North by Northwest',
 'Vertigo',
 "Singin' in the Rain",
 'Citizen Kane',
 'M - Eine Stadt sucht einen Mörder']

In [41]:
for i in soup.find_all('div',class_='ratings-bar'):
    Rating.append(i.find('strong').text)
for i in soup2.find_all('div',class_='ratings-bar'):
    Rating.append(i.find('strong').text)
Rating

['9.3',
 '9.2',
 '9.0',
 '9.0',
 '9.0',
 '9.0',
 '8.9',
 '8.9',
 '8.9',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.8',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.7',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.6',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.5',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.4',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3',
 '8.3']

In [42]:
Years = []
for i in soup.find_all('div',class_='lister-item-content'):
    Years.append (i.find('span',class_='lister-item-year text-muted unbold').text)
for i in soup2.find_all('div',class_='lister-item-content'):
    Years.append (i.find('span',class_='lister-item-year text-muted unbold').text)
Years

['(1994)',
 '(1972)',
 '(2021)',
 '(2008)',
 '(1974)',
 '(1957)',
 '(2003)',
 '(1994)',
 '(1993)',
 '(2010)',
 '(1999)',
 '(2001)',
 '(1994)',
 '(1966)',
 '(2002)',
 '(1999)',
 '(1990)',
 '(1980)',
 '(1975)',
 '(2019)',
 '(2014)',
 '(2002)',
 '(2001)',
 '(1998)',
 '(1999)',
 '(1997)',
 '(1995)',
 '(1991)',
 '(1977)',
 '(1962)',
 '(1954)',
 '(1946)',
 '(2014)',
 '(2011)',
 '(2006)',
 '(2006)',
 '(2002)',
 '(2000)',
 '(1998)',
 '(1995)',
 '(1994)',
 '(1994)',
 '(1991)',
 '(1988)',
 '(1988)',
 '(1985)',
 '(1968)',
 '(1960)',
 '(1954)',
 '(1942)',
 '(1936)',
 '(1931)',
 '(2020)',
 '(2018)',
 '(2019)',
 '(2016)',
 '(2018)',
 '(2019)',
 '(2018)',
 '(I) (2017)',
 '(2012)',
 '(2012)',
 '(2009)',
 '(2007)',
 '(2008)',
 '(2006)',
 '(2003)',
 '(2000)',
 '(1997)',
 '(1981)',
 '(1980)',
 '(1979)',
 '(1979)',
 '(1963)',
 '(1964)',
 '(1957)',
 '(1957)',
 '(1950)',
 '(1940)',
 '(2012)',
 '(2009)',
 '(2004)',
 '(2000)',
 '(1999)',
 '(1997)',
 '(1995)',
 '(1995)',
 '(1992)',
 '(1985)',
 '(1986)',
 '(1984)',
 '(1984)',
 '(1983)',
 '(1981)',
 '(1968)',
 '(1959)',
 '(1958)',
 '(1952)',
 '(1941)',
 '(1931)']

In [43]:
import pandas as pd
df=pd.DataFrame({'Name':Name,'Rating':Rating,'Year':Years})
df

                                 Name Rating    Year
0            The Shawshank Redemption    9.3  (1994)
1                       The Godfather    9.2  (1972)
2             Spider-Man: No Way Home    9.0  (2021)
3                     The Dark Knight    9.0  (2008)
4              The Godfather: Part II    9.0  (1974)
..                                ...    ...     ...
95                 North by Northwest    8.3  (1959)
96                            Vertigo    8.3  (1958)
97                Singin' in the Rain    8.3  (1952)
98                       Citizen Kane    8.3  (1941)
99  M - Eine Stadt sucht einen Mörder    8.3  (1931)

[100 rows x 3 columns]